#!/usr/bin/perl
# ------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------
# This program loads an IVIL file with XML::Simple and dumps the data with
# Data::Dumper
# ------------------------------------------------------------------------------
# Copyright (C) 2010  Schuberg Philis, Frank Breedijk - Under GPLv3
# ------------------------------------------------------------------------------

use strict;
use XML::Simple;
use Data::Dumper;

print Dumper( 
	XMLin(
		(join "", <>),
		forcearray 	=> [ 'finding', 'references' ],
		KeyAttr		=> undef,
	) 
);
